In [1]:
name = "Stacy"
hourly_wage = 20
hours = 18

weekly_pay = hourly_wage * hours
print (f"{name} makes ${weekly_pay} per week.")

Stacy makes $360 per week.

In [2]:
temps = [61, 65, 72, 58, 70, 74, 68]
days = 0
for t in temps:
	if t > 65:
		days = days + 1
print(days)

4

In [3]:
def to_celsius(f):
    return (f - 32) * 5/9

print(round(to_celsius(temps[0]), 1))

16.1

In [4]:
movie = {"title": "Ender's Game", "year": 2013, "rating": 3}
for key, value in movie.items():
    print (key, ":", value)

title : Ender's Game
year : 2013
rating : 3

In [5]:
import pandas as pd
df = pd.read_csv("chickwts.csv", index_col=0)
display(df.head())
display(df.shape)
display(df.describe())

   weight       feed
1     179  horsebean
2     160  horsebean
3     136  horsebean
4     227  horsebean
5     217  horsebean

(71, 2)

           weight
count   71.000000
mean   261.309859
std     78.073700
min    108.000000
25%    204.500000
50%    258.000000
75%    323.500000
max    423.000000

Step 6: Interpret describe():

The biggest thing that I notice here is that the "50%" data and the "mean" data values are pretty close to one another. I believe that this would mean that our data is probably decently accurate.

AI Assistance

In this lab I asked ChatGPT 

`I am working in a jupyter notebook. Here is my code:
import pandas as pd
df = pd.read_csv("chickwts.csv")
df.head()
df.shape
df.describe()
Why is the output only showing the final line of df.describe()`

It let me know "In a Jupyter cell, Python evaluates all the lines, but only automatically displays the result of the last expression" and then recommended that I use `display()` in order to see all outputs. 

I then inquired:
`Why does the describe include the first column which is just the numbers of each row`

It responded that "Most likely, that "first column" isn't actually being treated as the DataFrame's row index. It's probably a column that was saved into chickwts.csv" and recommended "If that first column is simply the row numbers, you can tell pandas to use it as the index:" with `df = pd.read_csv("chickwts.csv", index_col=0)
` 

I did as recommended and it cleaned up my output a lot.